Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebPlatforma.Models;
using WebPlatforma.Entites;
using System.IO;
using MongoDB.Driver;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace WebPlatforma.Controllers
{
    public class AdminController : Controller
    {
        AdminModel am = new AdminModel();
        PorukaModel bm = new PorukaModel();
        BlanketModel blm = new BlanketModel();
        KnjigaModel km = new KnjigaModel();
        PredavanjeModel pm = new PredavanjeModel();
        KomentarModel kkm = new KomentarModel();

        // GET: Admin
        public ActionResult Index()
        {
            ViewBag.svePoruke = bm.FindPoruke();
            ViewBag.brojPoruka = bm.FindPoruke().Count();
            //ViewBag.procitanePoruke = bm.FindProcitane();
            return View();
        }

        [HttpPost]
        public ActionResult AdminHome(String email, String sifra)
        {
            Admin a = am.Find(email, sifra);
            if (a != null)
			{
				 ViewBag.svePoruke = bm.FindPoruke();
                 ViewBag.brojPoruka = bm.FindPoruke().Count();
				 return View("Index", a);
			}
            else
            {
                TempData["message"] = "<script>alert('Neispravno uneti podaci');</script>";
                ViewBag.neispravnoLogovanje = "Pogresno uneti podaci";
                return RedirectToAction(nameof(HomeController.Index), "Home");
            }
        }

		#region poruka
		
		[HttpGet]
        public ActionResult DeletePoruka(String id)
        {
            bm.Delete(id);
            return RedirectToAction("Index");
        }
        #endregion

        #region predavanje
        [HttpGet]
        public ActionResult AdminPredavanja(String pretraga)
        {
            ViewBag.predavanja = pm.FindAll(pretraga);
            return View();
        }
		
        public ActionResult AdminPredavanja()
        {
            ViewBag.predavanja = pm.FindAll("");
            return View();
        }

        [HttpGet]
        public ActionResult AdminAddPredavanje()
        {
            return View("AdminAddPredavanje", new Predavanje());
        }
        

        [HttpGet]
        public ActionResult DeletePredavanje(String id)
        {
            pm.Delete(id);
            return RedirectToAction("AdminPredavanja");
        }
		
		
        [HttpGet]
        public ActionResult AdminUpdatePredavanje(String id)
        {
            ViewBag.predavanje = pm.Find(new ObjectId(id));
            return View("AdminUpdatePredavanje");
        }


        #endregion

        #region blanket

        [HttpGet]
        public ActionResult AdminBlanketi(String pretraga)
        {
            ViewBag.blanketi = blm.FindAll(pretraga);
            return View();
        }

        public ActionResult AdminBlanketi()
        {
            ViewBag.blanketi = blm.FindAll("");
            return View();
        }

        [HttpGet]
        public ActionResult AdminAddBlanket()
        {
            return View("AdminAddBlanket", new Blanket());
        }

        [HttpGet]
        public ActionResult DeleteBlanket(String id)
        {
            blm.Delete(id);
            return RedirectToAction("AdminBlanketi");
        }

        [HttpGet]
        public ActionResult AdminUpdateBlanket(String id)
        {
            ViewBag.blanket = blm.Find(new ObjectId(id));
            return View("AdminUpdateBlanket");
        }

        public ActionResult AdminAboutBlanket(String id, String sort)
        {
            ViewBag.dokument = id;
            if (sort == "najnoviji")
                ViewBag.komentari = kkm.FindByDocumentSortNew(id);
            else if (sort == "najpopularniji")
                ViewBag.komentari = kkm.FindByDocumentSortPopular(id);
            else ViewBag.komentari = kkm.FindByDocument(id);
            return View();
        } 
        public ActionResult AdminAboutKnjiga(String id, String sort)
        {
            ViewBag.dokument = id;
            if (sort == "najnoviji")
                ViewBag.komentari = kkm.FindByDocumentSortNew(id);
            else if (sort == "najpopularniji")
                ViewBag.komentari = kkm.FindByDocumentSortPopular(id);
            else ViewBag.komentari = kkm.FindByDocument(id);
            return View();
        } 
        public ActionResult AdminAboutPredavanje(String id, String sort)
        {
            ViewBag.dokument = id;
            if (sort == "najnoviji")
                ViewBag.komentari = kkm.FindByDocumentSortNew(id);
            else if (sort == "najpopularniji")
                ViewBag.komentari = kkm.FindByDocumentSortPopular(id);
            else ViewBag.komentari = kkm.FindByDocument(id);
            return View();
        }



        #endregion

        #region knjiga

        [HttpGet]
        public ActionResult AdminKnjige(String pretraga)
        {
            ViewBag.knjige = km.FindAll(pretraga);
            return View();
        }
        
        public ActionResult AdminKnjige()
        {
            ViewBag.knjige = km.FindAll("");
            return View();
        }

        [HttpGet]
        public ActionResult AdminAddKnjiga()
        {
            return View("AdminAddKnjiga", new Knjiga());
        }
		
		[HttpGet]
        public ActionResult DeleteKnjiga(String id)
        {
            km.Delete(id);
            return RedirectToAction("AdminKnjige");
        }

        [HttpGet]
        public ActionResult AdminUpdateKnjiga(String id)
        {
            ViewBag.knjiga = km.Find(new ObjectId(id));
            return View("AdminUpdateKnjiga");
        }



        #endregion

        #region korisnik
        public ActionResult AdminKorisnici(String pretraga)
        {
            ViewBag.korisniciB = bm.FindZahtevBlanketi();
            ViewBag.korisniciK = bm.FindZahtevKnjige();
            ViewBag.korisniciP = bm.FindZahtevPredavanja();

            return View();
        }
        #endregion
    }
}

Controllers/KnjigaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebPlatforma.Entites;
using WebPlatforma.Models;
using System.IO;
using MongoDB.Driver;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using System.Net.Mail;

namespace WebPlatforma.Controllers
{
    public class KnjigaController : Controller
    {
        KnjigaModel km = new KnjigaModel();
        PorukaModel pm = new PorukaModel();
		KomentarModel kkm = new KomentarModel();
		
        // GET: Knjiga
        public ActionResult Index(String pretraga)
        {
            ViewBag.knjige = km.FindAll(pretraga);
            return View();
        }
		
		public ActionResult LikeKnjiga(String id)
        {
            Knjiga b = km.Find(new ObjectId(id));
            if (b.ocena == null)
                b.ocena = 0.ToString();
            int ocena = Int16.Parse(b.ocena);
            ocena++;
            b.ocena = ocena.ToString();
            km.Update(b);
            ViewBag.knjige = km.FindAll("");
            return View("Index");
        }
		
        [HttpGet]
        public ActionResult AddKnjiga()
        {
            return View("AddKnjiga", new Knjiga());
        }

        [HttpPost]
        public ActionResult AddKnjiga(Knjiga b, HttpPostedFileBase nazivFajla)
        {
            if (nazivFajla != null)
            {
                string path = Server.MapPath("~/Resources/");
                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }

                nazivFajla.SaveAs(path + Path.GetFileName(nazivFajla.FileName));
             b.nazivFajla = nazivFajla.FileName;
            }
             List<Poruka> zahteviNotifikacije = pm.FindZahtevKnjige();
            foreach (Poruka p in zahteviNotifikacije)
            {
                if (p.naslov == b.predmet)
                {
                    //salje email

                    var sub = "Nova knjiga " + b.predmet;
                    String poruka = "Na platformi je sada dostupan nova knjiga iz oblasti koju ste zahtevali. Link za preuzimanje materijala: https://localhost:44302/Resources/" + b.nazivFajla;
                    var body = poruka;
                    var smtp = new SmtpClient
                    {
                        Host = "smtp.gmail.com",
                        Port = 587,
                        EnableSsl = true,
                        DeliveryMethod = SmtpDeliveryMethod.Network,
                        UseDefaultCredentials = false,
                        Credentials = new System.Net.NetworkCredential("platformazaucenje@gmail.com", "ucenjePlatforma")
                    };
                    using (var mess = new MailMessage("platformazaucenje@gmail.com", p.emailKorisnika)
                    {
                        Subject = sub,
                        Body = body
                    })
                    {
                        smtp.Send(mess);
                    }
                }
            }

            km.Create(b);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult AdminAddKnjiga(Knjiga b, HttpPostedFileBase nazivFajla)
        {
            if (nazivFajla != null)
            {
                string path = Server.MapPath("~/Resources/");
                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }

                nazivFajla.SaveAs(path + Path.GetFileName(nazivFajla.FileName));
				
            b.nazivFajla = nazivFajla.FileName;
            }
          
			
			List<Poruka> zahteviNotifikacije = pm.FindZahtevKnjige();
            foreach (Poruka p in zahteviNotifikacije)
            {
                if (p.naslov == b.predmet)
                {
                    //salje email

                    var sub = "Nova knjiga " + b.predmet;
                    String poruka = "Na platformi je sada dostupan nova knjiga iz oblasti koju ste zahtevali. Link za preuzimanje materijala: https://localhost:44302/Resources/" + b.nazivFajla;
                    var body = poruka;
                    var smtp = new SmtpClient
                    {
                        Host = "smtp.gmail.com",
                        Port = 587,
                        EnableSsl = true,
                        DeliveryMethod = SmtpDeliveryMethod.Network,
                        UseDefaultCredentials = false,
                        Credentials = new System.Net.NetworkCredential("platformazaucenje@gmail.com", "ucenjePlatforma")
                    };
                    using (var mess = new MailMessage("platformazaucenje@gmail.com", p.emailKorisnika)
                    {
                        Subject = sub,
                        Body = body
                    })
                    {
                        smtp.Send(mess);
                    }
                }
            }


            km.Create(b);
            return RedirectToAction(nameof(AdminController.AdminKnjige), "Admin");
        }

        [HttpPost]
        public ActionResult AdminUpdateKnjiga(Knjiga b, HttpPostedFileBase trenutniFajl, String id)
        {
            var knjiga = km.Find(new ObjectId(id));
            Knjiga trKnjiga = knjiga;
            if(trenutniFajl != null)
            {
                string path = Server.MapPath("~/Resources/");
                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }

                trenutniFajl.SaveAs(path + Path.GetFileName(trenutniFajl.FileName));

                trKnjiga.nazivFajla = trenutniFajl.FileName;

            }
            trKnjiga.predmet = b.predmet;
            trKnjiga.autor= b.autor;
            trKnjiga.opis = b.opis;
            trKnjiga.ocena = b.ocena;
            km.Update(trKnjiga);
            return RedirectToAction(nameof(AdminController.AdminKnjige), "Admin");
        }
		
		 public ActionResult AboutKnjiga(String id, String sort)
        {
            ViewBag.dokument = id;
            if (sort == "najnoviji")
                ViewBag.komentari = kkm.FindByDocumentSortNew(id);
            else if (sort == "najpopularniji")
                ViewBag.komentari = kkm.FindByDocumentSortPopular(id);
            else ViewBag.komentari = kkm.FindByDocument(id);
            return View();
        }
    }
}

Views/Admin/AdminAboutBlanket.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap 4 Blog Post Comments Section Design</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<style>
.comments-details button.btn.dropdown-toggle,
.comments-details .total-comments {
    font-size: 18px;
    font-weight: 500;
    color: #5e5e5e;
}
.comments-details {
    padding: 15px 15px;
}
.comments .comments .dropdown,
.comments .dropup {
    position: relative;
}
.comments button {
    background-color: transparent;
    border: none;
}
.comments .comment-box {
    width: 100%;
    float: left;
    height: 100%;
    background-color: #FAFAFA;
    padding: 10px 10px 10px;
    margin-bottom: 15px;
    border-radius: 5px;
    border: 1px solid #ddd;
}
.comments .add-comment {
    background-color: transparent;
    border: none;
    position: relative;
    margin-bottom: 50px;
}
.comments .commenter-pic {
    width: 50px;
    height: 50px;
    display: inline-block;
    border-radius: 100%;
    border: 2px solid #fff;
    overflow: hidden;
    background-color: #fff;
}
.comments .add-comment .commenter-name {
    width: 100%;
    padding-left: 75px;
    position: absolute;
    top: 20px;
    left: 0px;
}
.comments .add-comment input {
    border-top: 0px;
    border-bottom: 1px solid #ccc;
    border-left: 0px;
    border-right: 0px;
    outline: 0px;
    box-shadow: none;
    border-radius: 0;
    width: 100%;
    padding: 0;
    font-weight: normal;
}
.comments .add-comment input:focus {
    border-color: #03a9f4;
    border-width: 2px;
}
.comments .add-comment button[type=submit] {
    background-color: #03a9f4;
    color: #fff;
    margin-right: 0px;
}
.comments .add-comment button {
    background-color: #f5f5f5;
    margin: 10px 5px;
    font-size: 14px;
    text-transform: uppercase;
    float: right;
}
.comments .commenter-name .comment-time {
    font-weight: normal;
    margin-left: 8px;
    font-size: 15px;
}
.comments p.comment-txt {
    font-size: 15px;
    border-bottom: 1px solid #ddd;
    padding: 0px 0px 15px;
}
.comments .commenter-name {
    display: inline-block;
    position: relative;
    top: -20px;
    left: 10px;
    font-size: 16px;
    font-weight: bold;
}
.comments .comment-meta {
    font-size: 14px;
    color: #333;
    padding: 2px 5px 0px;
    line-height: 20px;
    float: right;
}
.comments .reply-box {
    display: none;
}
.comments .replied {
    background-color: #fff;
    width: 95%;
    float: right;
    margin-top: 15px;
}

/*======Responsive CSS=======*/

.comments .commenter-pic {
    width: 40px;
    height: 40px;
}
.comments .commenter-name a{
  display: block;
  padding-top: 15px;
}
.comments .commenter-name .comment-time{
  display: block;
  margin-left: 0px;
}
}
</style>  
</head>
<body>
    @model WebPlatforma.Entites.Komentar
    @Html.Partial("_NavBarOut")

<div class="container">
  <div class="row">
    <div class="col-12">
        <div class="comments">
            <div class="comments-details">
                <span class="total-comments comments-sort"></span>
                <span class="dropdown">
                    <button type="button" class="btn dropdown-toggle" data-toggle="dropdown">Sortiraj po <span class="caret"></span></button>
                    <div class="dropdown-menu">
                        <a href="@Url.Action("AdminAboutBlanket", "Admin", new { id = ViewBag.dokument, sort = "najnoviji"})">Najnoviji komentari</a>
                        <a href="@Url.Action("AdminAboutBlanket", "Admin", new { id = ViewBag.dokument, sort = "najpopularniji"})">Najpopularniji komentari</a>
                    </div>
                </span>
            </div>

           
                @if (ViewBag.komentari != null)
                {
                    foreach (var v in ViewBag.komentari)
                    {

        <div class="comment-box">

            <span class="commenter-name">
                <a href="#">@v.imeKorisnika</a> <span class="comment-time">@v.vreme</span>
            </span>
            <p class="comment-txt more" >@v.tekstKomentara</p>
            <div class="comment-meta">
                <a href="@Url.Action("LikeKomentar", "Komentar", new { id = v.id})" data-toggle="tooltip" title="Svidja mi se"><span class="fa fa-thumbs-o-up" fill="currentColor"></span></a>
                <button data-toggle="tooltip" class="comment-like">@v.ocena</button>
				<a href="@Url.Action("DeleteKomentar", "Komentar", new { id = v.id})" data-toggle="tooltip" title="Obrisi"><span class="fa fa-trash" fill="currentColor"></span></a>
               
            </div>

           
            

            @foreach (var k in v.odgovori)
            {
                <div class="comment-box replied">
                    
                    <span class="commenter-name">
                        <a href="#"></a> <span class="comment-time">@k.vreme</span>
                    </span>
                    <p class="comment-txt more">@k.tekstKomentara</p>
                    <div class="comment-meta">
					<a href="@Url.Action("LikeSubKomentar", "Komentar", new { id = @v.id, idPodKom = k.id})" data-toggle="tooltip" title="Svidja mi se"><span class="fa fa-thumbs-o-up" fill="currentColor"></span></a>
                        <button class="comment-like"> @k.ocena</button>
					<a href="@Url.Action("DislikeSubKomentar", "Komentar", new { id = @v.id, idPodKom = k.id})" data-toggle="tooltip" title="Svidja mi se"><span class="fa fa-thumbs-o-down" fill="currentColor"></span></a>
                        <button class="comment-dislike">@k.negativnaOcena</button>
                    <a href="@Url.Action("DeleteSubKomentar", "Komentar", new { id = @v.id, idPodKom = k.id})" data-toggle="tooltip" title="Obrisi"><span class="fa fa-trash" fill="currentColor"></a>
                    </div>
                </div>

            }

        </div>
						
						

                    }
                }
				
				
            </div>
    </div>
  </div>
</div>
</body>
</html>


<script>
// Reply box popup JS
$(document).ready(function(){
    $(".reply-popup").click(function(){
    $(".reply-box").toggle();
  });
});
</script>

Views/Admin/AdminAddKnjiga.cshtml
@{
    ViewBag.Title = "View";
    Layout = null;
}
<!doctype html>
<html lang="en">
<head>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">

    <!------ Include the above in your HEAD tag ---------->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Knjige</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.17.1/dist/bootstrap-table.min.css">

    <link href="~/Content/AddKnjiga.css" rel="stylesheet">
</head>
<body>
    @Html.Partial("_NavBarOut")
    <!--ucitava sve iz baze i ubacuje fajl u Resources-->
    <div class="klasaDiv">
        @using (Html.BeginForm("AdminAddKnjiga", "Knjiga", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div id="addbox" style=" margin-top:50px" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                <div class="panel panel-info">

                    <div class="panel-body">
                        <form method="post" action=".">
                            <input type='hidden' name='csrfmiddlewaretoken' value='XFe2rTYl9WOpV8U6X5CfbIuOZOELJ97S' />


                            <div class="form-horizontal" method="post">
                                <input type='hidden' name='csrfmiddlewaretoken' value='XFe2rTYl9WOpV8U6X5CfbIuOZOELJ97S' />

                                <div id="div_id_predmet" class="form-group required">
                                    <label for="id_predmet" class="control-label col-md-4  requiredField"> Naziv predmeta<span class="asteriskField">*</span> </label>
                                    <div class="controls col-md-8 ">
                                        <input class="input-md  textinput textInput form-control" id="id_predmet" maxlength="50" name="predmet" placeholder="Unesite naziv predmeta" style="margin-bottom: 10px" type="text" />
                                    </div>
                                </div>

                                <div id="div_id_autor" class="form-group required">
                                    <label for="id_autor" class="control-label col-md-4  requiredField">Autor<span class="asteriskField">*</span> </label>
                                    <div class="controls col-md-8 ">
                                        <input class="input-md textinput textInput form-control" id="id_autor" name="autor" placeholder="Unesite autora knjige" style="margin-bottom: 10px" type="text" />
                                    </div>
                                </div>

                                <div id="div_id_opis" class="form-group required">
                                    <label for="id_opis" class="control-label col-md-4  requiredField"> Opis<span class="asteriskField">*</span> </label>
                                    <div class="controls col-md-8 ">
                                        <input class="input-md textinput textInput form-control" id="id_opis" name="opis" placeholder="Unesite kratak opis knjige" style="margin-bottom: 10px" type="text" />
                                    </div>
                                </div>

                                <div id="div_id_dok" class="form-group required">
                                    <label for="id_dok" class="control-label col-md-4  requiredField"> Izaberite dokument<span class="asteriskField">*</span> </label>
                                    <div class="controls col-md-8 ">
                                        <input type="file" name="nazivFajla" />
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="aab controls col-md-4 "></div>
                                    <div class="controls col-md-8 ">
                                        <input type="submit" name="addKnjiga" value="Dodajte knjigu" class="btn-info" id="submitKnjiga" />

                                    </div>
                                </div>

                            </div>

                        </form>
                    </div>
                </div>
            </div>
        }
    </div>

</body>
</html>

Views/Admin/AdminUpdateKnjiga.cshtml
@{
    ViewBag.Title = "View";
    Layout = null;
}
<!doctype html>
<html lang="en">
<head>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">

    <!------ Include the above in your HEAD tag ---------->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Knjige</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.17.1/dist/bootstrap-table.min.css">

    <link href="~/Content/AddKnjiga.css" rel="stylesheet">
</head>
<body>
    @model WebPlatforma.Entites.Knjiga
    @Html.Partial("_NavBarOut")
    <!--ucitava sve iz baze i ubacuje fajl u Resources-->
    <div class="klasaDiv">
        @using (Html.BeginForm("AdminUpdateKnjiga", "Knjiga", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div id="addbox" style=" margin-top:50px" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                <div class="panel panel-info">

                    <div class="panel-body">
                        <form method="post" action=".">
                            <input type='hidden' name='csrfmiddlewaretoken' value='XFe2rTYl9WOpV8U6X5CfbIuOZOELJ97S' />


                            <div class="form-horizontal" method="post">
                                <input type='hidden' name='csrfmiddlewaretoken' value='XFe2rTYl9WOpV8U6X5CfbIuOZOELJ97S' />

                                <div id="div_id_predmet" class="form-group required">
                                    <label for="id_predmet" class="control-label col-md-4  requiredField"> Naziv predmeta<span class="asteriskField">*</span> </label>
                                    <div class="controls col-md-8 ">
                                        <input class="input-md  textinput textInput form-control" id="id_predmet" maxlength="50" name="predmet" style="margin-bottom: 10px" type="text" value="@ViewBag.knjiga.predmet" />
                                    </div>
                                </div>

                                <div id="div_id_autor" class="form-group required">
                                    <label for="id_autor" class="control-label col-md-4  requiredField">Autor<span class="asteriskField">*</span> </label>
                                    <div class="controls col-md-8 ">
                                        <input class="input-md textinput textInput form-control" id="id_autor" name="autor" value="@ViewBag.knjiga.autor" style="margin-bottom: 10px" type="text" />
                                    </div>
                                </div>

                                <div id="div_id_opis" class="form-group required">
                                    <label for="id_opis" class="control-label col-md-4  requiredField"> Opis<span class="asteriskField">*</span> </label>
                                    <div class="controls col-md-8 ">
                                        <input class="input-md textinput textInput form-control" id="id_opis" name="opis" value="@ViewBag.knjiga.opis" style="margin-bottom: 10px" type="text" />
                                    </div>
                                </div>

                                <div id="div_id_fajl" class="form-group required">
                                    <label for="id_fajl" class="control-label col-md-4  requiredField"> Dokument<span class="asteriskField">*</span> </label>
                                    <div class="controls col-md-8 ">
                                        <a href="~/Resources/@ViewBag.knjiga.nazivFajla">@ViewBag.knjiga.nazivFajla</a>
                                    </div>
                                </div>


                                <div id="div_id_dok" class="form-group required">
                                    <label for="id_dok" class="control-label col-md-4  requiredField"> Promenite dokument<span class="asteriskField">*</span> </label>
                                    <div class="controls col-md-8 ">
                                        <input type="file" name="trenutniFajl" />
                                    </div>
                                </div>

                               <input data-val="true"
                                   data-val-number="The field StudentId must be a number."
                                   data-val-required="The StudentId field is required."
                                   id="StudentId"
                                   name="id"
                                   type="hidden"
                                   value="@ViewBag.knjiga.id" />

                                <div class="form-group">
                                    <div class="aab controls col-md-4 "></div>
                                    <div class="controls col-md-8 ">
                                        <input type="submit" name="updateKnjiga" value="Azurirajte knjigu" class="btn-info" id="submitKnjiga" />

                                    </div>
                                </div>





                            </div>

                        </form>
                    </div>
                </div>
            </div>
        }
    </div>

</body>
</html>