Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebPlatforma.Models;
using WebPlatforma.Entites;
using System.IO;
using MongoDB.Driver;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace WebPlatforma.Controllers
{
    public class AdminController : Controller
    {
        AdminModel am = new AdminModel();
        PorukaModel bm = new PorukaModel();
        BlanketModel blm = new BlanketModel();
        KnjigaModel km = new KnjigaModel();
        PredavanjeModel pm = new PredavanjeModel();
        KomentarModel kkm = new KomentarModel();

        // GET: Admin
        public ActionResult Index()
        {
            ViewBag.svePoruke = bm.FindPoruke();
            ViewBag.brojPoruka = bm.FindPoruke().Count();
            //ViewBag.procitanePoruke = bm.FindProcitane();
            return View();
        }

        [HttpPost]
        public ActionResult AdminHome(String email, String sifra)
        {
            Admin a = am.Find(email, sifra);
            if (a != null)
			{
				 ViewBag.svePoruke = bm.FindPoruke();
                 ViewBag.brojPoruka = bm.FindPoruke().Count();
				 return View("Index", a);
			}
            else
            {
                TempData["message"] = "<script>alert('Neispravno uneti podaci');</script>";
                ViewBag.neispravnoLogovanje = "Pogresno uneti podaci";
                return RedirectToAction(nameof(HomeController.Index), "Home");
            }
        }

		#region poruka
		
		[HttpGet]
        public ActionResult DeletePoruka(String id)
        {
            bm.Delete(id);
            return RedirectToAction("Index");
        }
        #endregion

        #region predavanje
        [HttpGet]
        public ActionResult AdminPredavanja(String pretraga)
        {
            ViewBag.predavanja = pm.FindAll(pretraga);
            return View();
        }
		
        public ActionResult AdminPredavanja()
        {
            ViewBag.predavanja = pm.FindAll("");
            return View();
        }

        [HttpGet]
        public ActionResult AdminAddPredavanje()
        {
            return View("AdminAddPredavanje", new Predavanje());
        }
        

        [HttpGet]
        public ActionResult DeletePredavanje(String id)
        {
            pm.Delete(id);
            return RedirectToAction("AdminPredavanja");
        }
		
		
        [HttpGet]
        public ActionResult AdminUpdatePredavanje(String id)
        {
            ViewBag.predavanje = pm.Find(new ObjectId(id));
            return View("AdminUpdatePredavanje");
        }


        #endregion

        #region blanket

        [HttpGet]
        public ActionResult AdminBlanketi(String pretraga)
        {
            ViewBag.blanketi = blm.FindAll(pretraga);
            return View();
        }

        public ActionResult AdminBlanketi()
        {
            ViewBag.blanketi = blm.FindAll("");
            return View();
        }

        [HttpGet]
        public ActionResult AdminAddBlanket()
        {
            return View("AdminAddBlanket", new Blanket());
        }

        [HttpGet]
        public ActionResult DeleteBlanket(String id)
        {
            blm.Delete(id);
            return RedirectToAction("AdminBlanketi");
        }

        [HttpGet]
        public ActionResult AdminUpdateBlanket(String id)
        {
            ViewBag.blanket = blm.Find(new ObjectId(id));
            return View("AdminUpdateBlanket");
        }

        public ActionResult AdminAboutBlanket(String id, String sort)
        {
            ViewBag.dokument = id;
            if (sort == "najnoviji")
                ViewBag.komentari = kkm.FindByDocumentSortNew(id);
            else if (sort == "najpopularniji")
                ViewBag.komentari = kkm.FindByDocumentSortPopular(id);
            else ViewBag.komentari = kkm.FindByDocument(id);
            return View();
        } 
        public ActionResult AdminAboutKnjiga(String id, String sort)
        {
            ViewBag.dokument = id;
            if (sort == "najnoviji")
                ViewBag.komentari = kkm.FindByDocumentSortNew(id);
            else if (sort == "najpopularniji")
                ViewBag.komentari = kkm.FindByDocumentSortPopular(id);
            else ViewBag.komentari = kkm.FindByDocument(id);
            return View();
        } 
        public ActionResult AdminAboutPredavanje(String id, String sort)
        {
            ViewBag.dokument = id;
            if (sort == "najnoviji")
                ViewBag.komentari = kkm.FindByDocumentSortNew(id);
            else if (sort == "najpopularniji")
                ViewBag.komentari = kkm.FindByDocumentSortPopular(id);
            else ViewBag.komentari = kkm.FindByDocument(id);
            return View();
        }



        #endregion

        #region knjiga

        [HttpGet]
        public ActionResult AdminKnjige(String pretraga)
        {
            ViewBag.knjige = km.FindAll(pretraga);
            return View();
        }
        
        public ActionResult AdminKnjige()
        {
            ViewBag.knjige = km.FindAll("");
            return View();
        }

        [HttpGet]
        public ActionResult AdminAddKnjiga()
        {
            return View("AdminAddKnjiga", new Knjiga());
        }
		
		[HttpGet]
        public ActionResult DeleteKnjiga(String id)
        {
            km.Delete(id);
            return RedirectToAction("AdminKnjige");
        }

        [HttpGet]
        public ActionResult AdminUpdateKnjiga(String id)
        {
            ViewBag.knjiga = km.Find(new ObjectId(id));
            return View("AdminUpdateKnjiga");
        }



        #endregion

        #region korisnik
        public ActionResult AdminKorisnici(String pretraga)
        {
            ViewBag.korisniciB = bm.FindZahtevBlanketi();
            ViewBag.korisniciK = bm.FindZahtevKnjige();
            ViewBag.korisniciP = bm.FindZahtevPredavanja();

            return View();
        }
        #endregion
    }
}

Controllers/PorukaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebPlatforma.Entites;
using WebPlatforma.Models;

namespace WebPlatforma.Controllers
{
    public class PorukaController : Controller
    {
        PorukaModel bm = new PorukaModel();
        // GET: Poruka
        public ActionResult Index()
        {
            ViewBag.poruke= bm.FindPoruke();
           // ViewBag.procitanePoruke = bm.FindProcitane();
            return View();
        }

        [HttpPost]
        public ActionResult AddPoruka(Poruka b)
        {
            bm.Create(b);
            return RedirectToAction(nameof(HomeController.Index), "Home");
        }


    }
}

Views/Shared/_CommentBlanket.cshtml
<!DOCTYPE html>

<html>
<head>
    <!------ Include the above in your HEAD tag ---------->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Admin</title>

   
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

    <link href="~/Content/Proba.css" rel="stylesheet">
</head>
<body>
    <!--Section: Contact v.2-->
    <section class="mb-4">

        <!--Section heading-->
        <h4 class="h1-responsive font-weight-bold text-center my-4">Kontaktirajte nas</h4>
        <!--Section description-->
        <p class="text-center w-responsive mx-auto mb-5">
            Niste pronasli odgovarajuci dokument? Prijavite se i nas tim ce Vas kontaktirati kada dokument bude dostupan na Platformi.
        </p>
        @using (Html.BeginForm("AddPoruka", "Poruka", FormMethod.Post))
        {
            <div class="row">

                <!--Grid column-->
                <div class="col-md-9 mb-md-0 mb-5">
                    <form id="contact-form" name="contact-form" method="POST">

                        <!--Grid row-->
                        <div class="row">

                            <!--Grid column-->
                            <div class="col-md-6">
                                <div class="md-form mb-0">
								 <label for="name" class="">Ime</label>
                                    <input type="text" id="name" name="ime" class="form-control">
                                   
                                </div>
                            </div>
                            <!--Grid column-->
                            <!--Grid column-->
                            <div class="col-md-6">
                                <div class="md-form mb-0">
								<label for="email" class="">Email</label>
                                    <input type="text" id="email" name="emailKorisnika" class="form-control">
                                    
                                </div>
                            </div>

                            <input type="text" name="zahtev" value="zahtevBlanket" hidden>

                        </div>
                        <!--Grid row-->
                        <!--Grid row-->
                        <div class="row">
                            <div class="col-md-12">
                                <div class="md-form mb-0">
								<label for="subject" class="">Predmet</label>
                                    <input type="text" id="subject" name="naslov" class="form-control">
                                    
                                </div>
                            </div>
                        </div>
                        <!--Grid row-->
                        <!--Grid row-->
                        <div class="row">

                            <!--Grid column-->
                            <div class="col-md-12">

                                <div class="md-form">
								<label for="message">Poruka</label>
                                    <textarea type="text" id="message" name="sadrzajPoruke" rows="2" class="form-control md-textarea"></textarea>
                                    
                                </div>

                            </div>
                        </div>
                        <!--Grid row-->

                    </form>
                        <div class="text-center text-md-left">
                            <input class="btn btn-primary" type="submit" value="Posalji">
                        </div>
                    
                    <div class="status"></div>
                </div>
                <!--Grid column-->
                <!--Grid column-->
                <div class="col-md-3 text-center">
                    <ul class="list-unstyled mb-0">
                        <li>
                            <i class="fas fa-map-marker-alt fa-2x"></i>
                            <p>Nis, Srbija</p>
                        </li>

                        <li>
                            <i class="fas fa-phone mt-4 fa-2x"></i>
                            <p> 234 567 </p>
                        </li>

                        <li>
                            <i class="fas fa-envelope mt-4 fa-2x"></i>
                            <p>platformazaucenje@gmail.com</p>
                        </li>
                    </ul>
                </div>
                <!--Grid column-->

            </div>
        }
        </section>
    <!--Section: Contact v.2-->
</body>
</html>

Views/Shared/_CommentKnjiga.cshtml
<!DOCTYPE html>

<html>
<head>
    <!------ Include the above in your HEAD tag ---------->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Admin</title>

   
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

    <link href="~/Content/Proba.css" rel="stylesheet">
</head>
<body>
    <!--Section: Contact v.2-->
    <section class="mb-4">

        <!--Section heading-->
        <h4 class="h1-responsive font-weight-bold text-center my-4">Kontaktirajte nas</h4>
        <!--Section description-->
        <p class="text-center w-responsive mx-auto mb-5">
            Niste pronasli odgovarajuci dokument? Prijavite se i nas tim ce Vas kontaktirati kada dokument bude dostupan na Platformi.
        </p>
        @using (Html.BeginForm("AddPoruka", "Poruka", FormMethod.Post))
        {
            <div class="row">

                <!--Grid column-->
                <div class="col-md-9 mb-md-0 mb-5">
                    <form id="contact-form" name="contact-form" method="POST">

                        <!--Grid row-->
                        <div class="row">

                            <!--Grid column-->
                            <div class="col-md-6">
                                <div class="md-form mb-0">
								 <label for="name" class="">Ime</label>
                                    <input type="text" id="name" name="ime" class="form-control">
                                   
                                </div>
                            </div>
                            <!--Grid column-->
                            <!--Grid column-->
                            <div class="col-md-6">
                                <div class="md-form mb-0">
								<label for="email" class="">Email</label>
                                    <input type="text" id="email" name="emailKorisnika" class="form-control">
                                    
                                </div>
                            </div>

                            <input type="text" name="zahtev" value="zahtevKnjiga" hidden>

                        </div>
                        <!--Grid row-->
                        <!--Grid row-->
                        <div class="row">
                            <div class="col-md-12">
                                <div class="md-form mb-0">
								<label for="subject" class="">Predmet</label>
                                    <input type="text" id="subject" name="naslov" class="form-control">
                                    
                                </div>
                            </div>
                        </div>
                        <!--Grid row-->
                        <!--Grid row-->
                        <div class="row">

                            <!--Grid column-->
                            <div class="col-md-12">

                                <div class="md-form">
								<label for="message">Poruka</label>
                                    <textarea type="text" id="message" name="sadrzajPoruke" rows="2" class="form-control md-textarea"></textarea>
                                    
                                </div>

                            </div>
                        </div>
                        <!--Grid row-->

                    </form>
                        <div class="text-center text-md-left">
                            <input class="btn btn-primary" type="submit" value="Posalji">
                        </div>
                    
                    <div class="status"></div>
                </div>
                <!--Grid column-->
                <!--Grid column-->
                <div class="col-md-3 text-center">
                    <ul class="list-unstyled mb-0">
                        <li>
                            <i class="fas fa-map-marker-alt fa-2x"></i>
                            <p>Nis, Srbija</p>
                        </li>

                        <li>
                            <i class="fas fa-phone mt-4 fa-2x"></i>
                            <p> 234 567 </p>
                        </li>

                        <li>
                            <i class="fas fa-envelope mt-4 fa-2x"></i>
                            <p>platformazaucenje@gmail.com</p>
                        </li>
                    </ul>
                </div>
                <!--Grid column-->

            </div>
        }
        </section>
    <!--Section: Contact v.2-->
</body>
</html>

Views/Shared/_CommentPredavanje.cshtml
<!DOCTYPE html>

<html>
<head>
    <!------ Include the above in your HEAD tag ---------->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Admin</title>

   
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

    <link href="~/Content/Proba.css" rel="stylesheet">
</head>
<body>
    <!--Section: Contact v.2-->
    <section class="mb-4">

        <!--Section heading-->
        <h4 class="h1-responsive font-weight-bold text-center my-4">Kontaktirajte nas</h4>
        <!--Section description-->
        <p class="text-center w-responsive mx-auto mb-5">
            Niste pronasli odgovarajuci dokument? Prijavite se i nas tim ce Vas kontaktirati kada dokument bude dostupan na Platformi.
        </p>
        @using (Html.BeginForm("AddPoruka", "Poruka", FormMethod.Post))
        {
            <div class="row">

                <!--Grid column-->
                <div class="col-md-9 mb-md-0 mb-5">
                    <form id="contact-form" name="contact-form" method="POST">

                        <!--Grid row-->
                        <div class="row">

                            <!--Grid column-->
                            <div class="col-md-6">
                                <div class="md-form mb-0">
								 <label for="name" class="">Ime</label>
                                    <input type="text" id="name" name="ime" class="form-control">
                                   
                                </div>
                            </div>
                            <!--Grid column-->
                            <!--Grid column-->
                            <div class="col-md-6">
                                <div class="md-form mb-0">
								<label for="email" class="">Email</label>
                                    <input type="text" id="email" name="emailKorisnika" class="form-control">
                                    
                                </div>
                            </div>

                            <input type="text" name="zahtev" value="zahtevPredavanje" hidden>

                        </div>
                        <!--Grid row-->
                        <!--Grid row-->
                        <div class="row">
                            <div class="col-md-12">
                                <div class="md-form mb-0">
								<label for="subject" class="">Predmet</label>
                                    <input type="text" id="subject" name="naslov" class="form-control">
                                    
                                </div>
                            </div>
                        </div>
                        <!--Grid row-->
                        <!--Grid row-->
                        <div class="row">

                            <!--Grid column-->
                            <div class="col-md-12">

                                <div class="md-form">
								<label for="message">Poruka</label>
                                    <textarea type="text" id="message" name="sadrzajPoruke" rows="2" class="form-control md-textarea"></textarea>
                                    
                                </div>

                            </div>
                        </div>
                        <!--Grid row-->

                    </form>
                        <div class="text-center text-md-left">
                            <input class="btn btn-primary" type="submit" value="Posalji">
                        </div>
                    
                    <div class="status"></div>
                </div>
                <!--Grid column-->
                <!--Grid column-->
                <div class="col-md-3 text-center">
                    <ul class="list-unstyled mb-0">
                        <li>
                            <i class="fas fa-map-marker-alt fa-2x"></i>
                            <p>Nis, Srbija</p>
                        </li>

                        <li>
                            <i class="fas fa-phone mt-4 fa-2x"></i>
                            <p> 234 567 </p>
                        </li>

                        <li>
                            <i class="fas fa-envelope mt-4 fa-2x"></i>
                            <p>platformazaucenje@gmail.com</p>
                        </li>
                    </ul>
                </div>
                <!--Grid column-->

            </div>
        }
        </section>
    <!--Section: Contact v.2-->
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/Home.css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_NavBar.cshtml
<html>
<body>
	@using (Html.BeginForm("AdminHome", "Admin", FormMethod.Post))
	{
		<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
			<div class="container">
				<!--<img class="navbar-brand" src="~/Resources/logoSova.png" style="height: 30px" />-->
				<a class="navbar-brand" href="Home">Platforma za ucenje</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarResponsive">
					<ul class="navbar-nav ml-auto">
						<li class="nav-item active">
							<a class="nav-link" href="https://localhost:44302/">
								Pocetna
								<span class="sr-only">(current)</span>
							</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="https://localhost:44302/Home/About">O nama</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="https://localhost:44302/Home/Contact">Kontakt</a>
						</li>
						<li class="nav-item">

							<a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle mr-4">Uloguj se</a>
							<div class="dropdown-menu action-form">
								<form action="/examples/actions/confirmation.php" method="post">

									<div class="form-group">
										<input type="text" class="form-control" name="email" placeholder="Username" required="required">
									</div>
									<div class="form-group">
										<input type="password" class="form-control" name="sifra" placeholder="Password" required="required">
									</div>
									<input type="submit" class="btn btn-primary btn-block" value="Login">
									
								</form>
							</div>

						</li>
					</ul>
				</div>
			</div>
		</nav>
	}
</body>
</html>
<style>
body {
	font-family: 'Varela Round', sans-serif;
}
.form-control {
	box-shadow: none;
	font-weight: normal;
	font-size: 13px;
}
.navbar {
	background: #fff;
	padding-left: 16px;
	padding-right: 16px;
	border-bottom: 1px solid #dfe3e8;
	border-radius: 0;
}
.nav-link img {
	border-radius: 50%;
	width: 36px;
	height: 36px;
	margin: -8px 0;
	float: left;
	margin-right: 10px;
}
.navbar .navbar-brand {
	padding-left: 0;
	font-size: 20px;
	padding-right: 50px;
}
.navbar .navbar-brand b {
	color: #33cabb;
}
.navbar .form-inline {
	display: inline-block;
}
.navbar a {
	color: #888;
	font-size: 15px;
}
.navbar .sign-up-btn {
	min-width: 110px;
	max-height: 36px;
}
.navbar .dropdown-menu {
	color: #999;
	font-weight: normal;
	border-radius: 1px;
	border-color: #e5e5e5;
	box-shadow: 0 2px 8px rgba(0,0,0,.05);
}
.navbar a, .navbar a:active {
	color: #888;
	padding: 8px 20px;
	background: transparent;
	line-height: normal;
}
.navbar .navbar-form {
	border: none;
}
.navbar .action-form {
	width: 280px;
	padding: 20px;
	left: auto;
	right: 0;
	font-size: 14px;
}
.navbar .action-form a {
	color: #33cabb;
	padding: 0 !important;
	font-size: 14px;
}
.navbar .action-form .hint-text {
    text-align: center;
    margin-bottom: 15px;
    font-size: 13px;
}
.navbar .btn-primary, .navbar .btn-primary:active {
	color: #fff;
	background: #999 !important;
	border: none;
}
.navbar .btn-primary:hover, .navbar .btn-primary:focus {
	color: #fff;
	background: #666 !important;
}
.navbar .social-btn .btn, .navbar .social-btn .btn:hover {
	color: #fff;
	margin: 0;
	padding: 0 !important;
	font-size: 13px;
	border: none;
	transition: all 0.4s;
	text-align: center;
	line-height: 34px;
	width: 47%;
	text-decoration: none;
}

.navbar .social-btn .btn i {
	margin-right: 5px;
	font-size: 16px;
	position: relative;
	top: 2px;
}
.or-seperator {
	margin-top: 32px;
	text-align: center;
	border-top: 1px solid #e0e0e0;
}
.or-seperator b {
	color: #666;
	padding: 0 8px;
	width: 30px;
	height: 30px;
	font-size: 13px;
	text-align: center;
	line-height: 26px;
	background: #fff;
	display: inline-block;
	border: 1px solid #e0e0e0;
	border-radius: 50%;
	position: relative;
	top: -15px;
	z-index: 1;
}
.navbar .action-buttons .dropdown-toggle::after {
	display: none;
}
.form-check-label input {
	position: relative;
	top: 1px;
}

</style>

Views/Shared/_NavBarOut.cshtml
<html>
<body>
    @using (Html.BeginForm("AdminHome", "Admin", FormMethod.Post))
    {
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
            <div class="container">
                <a class="navbar-brand" href="Home">Platforma za ucenje</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active">
                            <a href="https://localhost:44302/Admin" class="nav-link" mr-4>Pocetna </a>
                        </li>
                        
                        <li class="nav-item">

                            <a href="https://localhost:44302/" class="nav-link  mr-4">Izadji</a>
                           

                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    }
</body>
</html>
<style>
    body {
        font-family: 'Varela Round', sans-serif;
    }

    .form-control {
        box-shadow: none;
        font-weight: normal;
        font-size: 13px;
    }

    .navbar {
        background: #fff;
        padding-left: 16px;
        padding-right: 16px;
        border-bottom: 1px solid #dfe3e8;
        border-radius: 0;
    }

    .nav-link img {
        border-radius: 50%;
        width: 36px;
        height: 36px;
        margin: -8px 0;
        float: left;
        margin-right: 10px;
    }

    .navbar .navbar-brand {
        padding-left: 0;
        font-size: 20px;
        padding-right: 50px;
    }

        .navbar .navbar-brand b {
            color: #33cabb;
        }

    .navbar .form-inline {
        display: inline-block;
    }

    .navbar a {
        color: #888;
        font-size: 15px;
    }

    .navbar .sign-up-btn {
        min-width: 110px;
        max-height: 36px;
    }

    .navbar .dropdown-menu {
        color: #999;
        font-weight: normal;
        border-radius: 1px;
        border-color: #e5e5e5;
        box-shadow: 0 2px 8px rgba(0,0,0,.05);
    }

    .navbar a, .navbar a:active {
        color: #888;
        padding: 8px 20px;
        background: transparent;
        line-height: normal;
    }

    .navbar .navbar-form {
        border: none;
    }

    .navbar .action-form {
        width: 280px;
        padding: 20px;
        left: auto;
        right: 0;
        font-size: 14px;
    }

        .navbar .action-form a {
            color: #33cabb;
            padding: 0 !important;
            font-size: 14px;
        }

        .navbar .action-form .hint-text {
            text-align: center;
            margin-bottom: 15px;
            font-size: 13px;
        }

    .navbar .btn-primary, .navbar .btn-primary:active {
        color: #fff;
        background: #999 !important;
        border: none;
    }

        .navbar .btn-primary:hover, .navbar .btn-primary:focus {
            color: #fff;
            background: #666 !important;
        }

    .navbar .social-btn .btn, .navbar .social-btn .btn:hover {
        color: #fff;
        margin: 0;
        padding: 0 !important;
        font-size: 13px;
        border: none;
        transition: all 0.4s;
        text-align: center;
        line-height: 34px;
        width: 47%;
        text-decoration: none;
    }

        .navbar .social-btn .btn i {
            margin-right: 5px;
            font-size: 16px;
            position: relative;
            top: 2px;
        }

    .or-seperator {
        margin-top: 32px;
        text-align: center;
        border-top: 1px solid #e0e0e0;
    }

        .or-seperator b {
            color: #666;
            padding: 0 8px;
            width: 30px;
            height: 30px;
            font-size: 13px;
            text-align: center;
            line-height: 26px;
            background: #fff;
            display: inline-block;
            border: 1px solid #e0e0e0;
            border-radius: 50%;
            position: relative;
            top: -15px;
            z-index: 1;
        }

    .navbar .action-buttons .dropdown-toggle::after {
        display: none;
    }

    .form-check-label input {
        position: relative;
        top: 1px;
    }
</style>

Views/Shared/_Succes.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Success</title>
</head>
<body>
    <hgroup>
        <h2>Uspesna prijava!</h2>
    </hgroup>
</body>
</html>