Entities/Predavanje.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using MongoDB.Bson;
using MongoDB.Driver;
using MongoDB.Bson.Serialization.Attributes;

namespace WebPlatforma.Entites
{
    public class Predavanje
    {
        [BsonId]
        public ObjectId id { get; set; }

        [BsonElement("predmet")]
        public string predmet { get; set; }

        [BsonElement("vreme")]
        public string vreme { get; set; }

        [BsonElement("mesto")]
        public string mesto { get; set; }

        [BsonElement("ocena")]
        public string ocena { get; set; }

        [BsonElement("prijavljeniKorisnici")]
        public String prijavljeniKorisnici { get; set; }

        [BsonElement("predavac")]
        public String predavac { get; set; }

        public Predavanje()
        {
            //prijavljeniKorisnici = new List<String>();
        }
    }
}

Controllers/KomentarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebPlatforma.Entites;
using WebPlatforma.Models;
using MongoDB.Driver;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace WebPlatforma.Controllers
{
    public class KomentarController : Controller
    {
        KomentarModel km = new KomentarModel();
        // GET: Komentar
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddKomentar(Komentar k)
        {
            if(k.idKorisnika == null)
            {

            }

            km.Create(k);

            return RedirectToAction(nameof(BlanketController.AboutBlanket), "Blanket", new { id = k.dokument});
        }

        [HttpPost]
        public ActionResult AddSubKomentar(Komentar k, String glavniKomentar)
        {
            Komentar glavni = km.Find(new ObjectId(glavniKomentar));
            k.dokument = glavni.dokument;
            k.id = ObjectId.GenerateNewId();
            glavni.odgovori.Add(k);
            km.Update(glavni);
			
            return RedirectToAction(nameof(BlanketController.AboutBlanket), "Blanket", new { id = k.dokument});
        }

        public ActionResult LikeKomentar(String id)
        {
            Komentar b = km.Find(new ObjectId(id));
            if (b.ocena == null)
                b.ocena = 0.ToString();
            int ocena = Int16.Parse(b.ocena);
            ocena++;
            b.ocena = ocena.ToString();
            km.Update(b);
            ViewBag.komentari = km.FindByDocument(id);
			
            return RedirectToAction(nameof(BlanketController.AboutBlanket), "Blanket", new { id = b.dokument});
        }
		
		public ActionResult LikeSubKomentar(String id, String idPodKom)
        {
            Komentar b = km.Find(new ObjectId(id));
            Komentar k = b.odgovori.Find(kom => kom.id == new ObjectId(idPodKom));
            if (k.ocena == null)
                k.ocena = 0.ToString();
            int ocena = Int16.Parse(k.ocena);
            ocena++;
            k.ocena = ocena.ToString();
            
            km.Update(b);
            ViewBag.komentari = km.FindByDocument(id);
			
            return RedirectToAction(nameof(BlanketController.AboutBlanket), "Blanket", new { id = b.dokument});
        }

        public ActionResult DislikeSubKomentar(String id, String idPodKom)
        {
            Komentar b = km.Find(new ObjectId(id));
            Komentar k = b.odgovori.Find(kom => kom.id == new ObjectId(idPodKom));
            if (k.negativnaOcena == null)
                k.negativnaOcena = 0.ToString();
            int ocena = Int16.Parse(k.negativnaOcena);
            ocena++;
            k.negativnaOcena = ocena.ToString();

            km.Update(b);
            ViewBag.komentari = km.FindByDocument(id);

            return RedirectToAction(nameof(BlanketController.AboutBlanket), "Blanket", new { id = b.dokument });
        }

        [HttpGet]
        public ActionResult DeleteSubKomentar(String id, String idPodKom)
        {
            Komentar b = km.Find(new ObjectId(id));
            Komentar k = b.odgovori.Find(kom => kom.id == new ObjectId(idPodKom));

            b.odgovori.Remove(k);

            km.Update(b);
            ViewBag.komentari = km.FindByDocument(id);

            return RedirectToAction(nameof(AdminController.AdminAboutBlanket), "Admin", new { id = b.dokument });
        }

        [HttpGet]
        public ActionResult DeleteKomentar(String id)
        {
            Komentar b = km.Find(new ObjectId(id));
            string dok = b.dokument;

            km.Delete(id);
            return RedirectToAction(nameof(AdminController.AdminAboutBlanket), "Admin", new { id = dok });
        }

    }
}

Controllers/PredavanjeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebPlatforma.Entites;
using WebPlatforma.Models;
using System.IO;
using MongoDB.Driver;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using System.Net.Mail;

namespace WebPlatforma.Controllers
{
    public class PredavanjeController : Controller
    {
        PredavanjeModel bm = new PredavanjeModel();
        PorukaModel pm = new PorukaModel();
		KomentarModel km = new KomentarModel();
		
        // GET: Predavanje/Index
        public ActionResult Index(String pretraga)
        {
            ViewBag.predavanja = bm.FindAll(pretraga);
            return View();
        }
		
		 public ActionResult LikePredavanje(String id)
        {
            Predavanje b = bm.Find(new ObjectId(id));
            if (b.ocena == null)
                b.ocena = 0.ToString();
            int ocena = Int16.Parse(b.ocena);
            ocena++;
            b.ocena = ocena.ToString();
            bm.Update(b);
            ViewBag.predavanja = bm.FindAll("");
            return View("Index");
        }


        [HttpGet]
        public ActionResult AddPredavanje()
        {
            return View("AddPredavanje", new Predavanje());
        }

        [HttpGet]
        public ActionResult PrijavaPredavanje(String id)
        {
            //pronadji predavanje iz baze na osnovu ida
            return View("PrijavaPredavanje", bm.Find(new ObjectId(id)));
        }

        //[HttpPost]
        //public ActionResult UpdatePredavanje(Predavanje p)
        //{
        //    var trPredavanje = bm.Find(p.id);
        //    trPredavanje.predmet = p.predmet;
        //    trPredavanje.predavac = p.predavac;
        //    trPredavanje.mesto = p.mesto;
        //    trPredavanje.vreme = p.vreme;
        //    trPredavanje.ocena = p.ocena;
        //    trPredavanje.prijavljeniKorisnici += p.prijavljeniKorisnici;
        //    bm.Update(trPredavanje);
        //    return RedirectToAction("Index");
        //}

        [HttpPost]
        public ActionResult UpdatePredavanje(String id, String prijavljeniKorisnici)
        {
            var trPredavanje = bm.Find(new ObjectId(id));
            trPredavanje.prijavljeniKorisnici +=  prijavljeniKorisnici + ", ";
            bm.Update(trPredavanje);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult DeletePredavanje(String id)
        {
            bm.Delete(id);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult AdminAddPredavanje(Predavanje b)
        {
            bm.Create(b);

            List<Poruka> zahteviNotifikacije = pm.FindZahtevPredavanja();
            foreach (Poruka p in zahteviNotifikacije)
            {
                if (p.naslov == b.predmet)
                {
                    //salje email

                    var sub = "Novo predavanje " + b.predmet;
                    String poruka = "Na platformi je sada dostupno novo predavanje iz oblasti koju ste zahtevali." + Environment.NewLine + "Link do predavanja: https://localhost:44302/Predavanje/Index";
                    var body = poruka;
                    var smtp = new SmtpClient
                    {
                        Host = "smtp.gmail.com",
                        Port = 587,
                        EnableSsl = true,
                        DeliveryMethod = SmtpDeliveryMethod.Network,
                        UseDefaultCredentials = false,
                        Credentials = new System.Net.NetworkCredential("platformazaucenje@gmail.com", "ucenjePlatforma")
                    };
                    using (var mess = new MailMessage("platformazaucenje@gmail.com", p.emailKorisnika)
                    {
                        Subject = sub,
                        Body = body
                    })
                    {
                        smtp.Send(mess);
                    }
                }
            }
			
			
            return RedirectToAction(nameof(AdminController.AdminPredavanja), "Admin");
        }

        [HttpPost]
        public ActionResult AdminUpdatePredavanje(Predavanje p, String id)
        {
            var predavanje = bm.Find(new ObjectId(id));

            Predavanje trPredavanje = predavanje;
            trPredavanje.predmet = p.predmet;
            trPredavanje.predavac = p.predavac;
            trPredavanje.mesto = p.mesto;
            trPredavanje.vreme = p.vreme;
            trPredavanje.ocena = p.ocena;
            trPredavanje.prijavljeniKorisnici += p.prijavljeniKorisnici;
            bm.Update(trPredavanje);
            
            return RedirectToAction(nameof(AdminController.AdminPredavanja), "Admin");
        }
		
		public ActionResult AboutPredavanje(String id, String sort)
        {
            ViewBag.dokument = id;
            if (sort == "najnoviji")
                ViewBag.komentari = km.FindByDocumentSortNew(id);
            else if (sort == "najpopularniji")
                ViewBag.komentari = km.FindByDocumentSortPopular(id);
            else ViewBag.komentari = km.FindByDocument(id);
            return View();
        }
    }
}

Views/Predavanje/AboutPredavanje.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bootstrap 4 Blog Post Comments Section Design</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <style>
        .comments-details button.btn.dropdown-toggle,
        .comments-details .total-comments {
            font-size: 18px;
            font-weight: 500;
            color: #5e5e5e;
        }

        .comments-details {
            padding: 15px 15px;
        }

        .comments .comments .dropdown,
        .comments .dropup {
            position: relative;
        }

        .comments button {
            background-color: transparent;
            border: none;
        }

        .comments .comment-box {
            width: 100%;
            float: left;
            height: 100%;
            background-color: #FAFAFA;
            padding: 10px 10px 10px;
            margin-bottom: 15px;
            border-radius: 5px;
            border: 1px solid #ddd;
        }

        .comments .add-comment {
            background-color: transparent;
            border: none;
            position: relative;
            margin-bottom: 50px;
        }

        .comments .commenter-pic {
            width: 50px;
            height: 50px;
            display: inline-block;
            border-radius: 100%;
            border: 2px solid #fff;
            overflow: hidden;
            background-color: #fff;
        }

        .comments .add-comment .commenter-name {
            width: 100%;
            padding-left: 75px;
            position: absolute;
            top: 20px;
            left: 0px;
        }

        .comments .add-comment input {
            border-top: 0px;
            border-bottom: 1px solid #ccc;
            border-left: 0px;
            border-right: 0px;
            outline: 0px;
            box-shadow: none;
            border-radius: 0;
            width: 100%;
            padding: 0;
            font-weight: normal;
        }

            .comments .add-comment input:focus {
                border-color: #03a9f4;
                border-width: 2px;
            }

        .comments .add-comment button[type=submit] {
            background-color: #03a9f4;
            color: #fff;
            margin-right: 0px;
        }

        .comments .add-comment button {
            background-color: #f5f5f5;
            margin: 10px 5px;
            font-size: 14px;
            text-transform: uppercase;
            float: right;
        }

        .comments .commenter-name .comment-time {
            font-weight: normal;
            margin-left: 8px;
            font-size: 15px;
        }

        .comments p.comment-txt {
            font-size: 15px;
            border-bottom: 1px solid #ddd;
            padding: 0px 0px 15px;
        }

        .comments .commenter-name {
            display: inline-block;
            position: relative;
            top: -20px;
            left: 10px;
            font-size: 16px;
            font-weight: bold;
        }

        .comments .comment-meta {
            font-size: 14px;
            color: #333;
            padding: 2px 5px 0px;
            line-height: 20px;
            float: right;
        }

        .comments .reply-box {
            display: none;
        }

        .comments .replied {
            background-color: #fff;
            width: 95%;
            float: right;
            margin-top: 15px;
        }

        /*======Responsive CSS=======*/

        .comments .commenter-pic {
            width: 40px;
            height: 40px;
        }

        .comments .commenter-name a {
            display: block;
            padding-top: 15px;
        }

        .comments .commenter-name .comment-time {
            display: block;
            margin-left: 0px;
        }
        }
    </style>
</head>
<body>
    @model WebPlatforma.Entites.Komentar
    @Html.Partial("_NavBar")

    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="comments">
                    <div class="comments-details">
                        <span class="total-comments comments-sort"></span>
                        <span class="dropdown">
                            <button type="button" class="btn dropdown-toggle" data-toggle="dropdown">Sortiraj po <span class="caret"></span></button>
                            <div class="dropdown-menu">
                                <a href="@Url.Action("AboutPredavanje", "Predavanje", new { id = ViewBag.dokument, sort = "najnoviji"})">Najnoviji komentari</a>
                                <a href="@Url.Action("AboutPredavanje", "Predavanje", new { id = ViewBag.dokument, sort = "najpopularniji"})">Najpopularniji komentari</a>
                            </div>
                        </span>
                    </div>

                    @using (Html.BeginForm("AddKomentar", "Komentar", FormMethod.Post))
                    {
                        <div class="comment-box add-comment">
                            <span class="commenter-pic">
                                <img src="~/Resources/user2.png" class="img-fluid">
                            </span>
                            <span class="commenter-name">
                                <input type="text" placeholder="Unesite komentar" name="tekstKomentara">
                                <input type="text" name="idKorisnika" hidden value="@ViewBag.korisnik">
                                <input hidden name="dokument" value="@ViewBag.dokument">
                                <button type="submit" class="btn btn-default">Dodaj komentar</button>
                            </span>
                        </div>
                    }
                    @if (ViewBag.komentari != null)
                    {
                        foreach (var v in ViewBag.komentari)
                        {

                            <div class="comment-box">

                                <span class="commenter-name">
                                    <a href="#">@v.imeKorisnika</a> <span class="comment-time">@v.vreme</span>
                                </span>
                                <p class="comment-txt more">@v.tekstKomentara</p>
                                <div class="comment-meta">
                                    <a href="@Url.Action("LikeKomentar", "Komentar", new { id = v.id})" data-toggle="tooltip" title="Svidja mi se"><span class="fa fa-thumbs-o-up" fill="currentColor"></span></a>
                                    <button data-toggle="tooltip" class="comment-like">@v.ocena</button>
                                    <button class="comment-reply reply-popup"><i class="fa fa-reply-all" aria-hidden="true"></i> Odgovori</button>
                                </div>


                                <div class="comment-box add-comment reply-box">

                                    <span class="commenter-name">
                                        @using (Html.BeginForm("AddSubKomentar", "Komentar", FormMethod.Post))
                                        {
                                            <input type="text" placeholder="Unesite komentar" name="tekstKomentara">
                                            <input hidden name="glavniKomentar" value="@v.id">
                                            <button type="submit" class="btn btn-default">Odgovori</button>
                                        }
                                        <button type="cancel" class="btn btn-default reply-popup">Izadji</button>
                                    </span>

                                </div>


                                @foreach (var k in v.odgovori)
                                {
                                    <div class="comment-box replied">

                                        <span class="commenter-name">
                                            <a href="#"></a> <span class="comment-time">@k.vreme</span>
                                        </span>
                                        <p class="comment-txt more">@k.tekstKomentara</p>
                                        <div class="comment-meta">
                                            <a href="@Url.Action("LikeSubKomentar", "Komentar", new { id = @v.id, idPodKom = k.id})" data-toggle="tooltip" title="Svidja mi se"><span class="fa fa-thumbs-o-up" fill="currentColor"></span></a>
                                            <button class="comment-like"> @k.ocena</button>
                                            <a href="@Url.Action("DislikeSubKomentar", "Komentar", new { id = @v.id, idPodKom = k.id})" data-toggle="tooltip" title="Svidja mi se"><span class="fa fa-thumbs-o-down" fill="currentColor"></span></a>
                                            <button class="comment-dislike">@k.negativnaOcena</button>
                                        </div>
                                    </div>

                                }

                            </div>



                        }
                    }


                </div>
            </div>
        </div>
    </div>
</body>
</html>


<script>
    // Reply box popup JS
    $(document).ready(function () {
        $(".reply-popup").click(function () {
            $(".reply-box").toggle();
        });
    });
</script>

Views/Predavanje/Index.cshtml
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Blanketi</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.17.1/dist/bootstrap-table.min.css">

    <link href="~/Content/Blanket.css" rel="stylesheet">
	<meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
</head>
<body>

    @Html.Partial("_NavBar")
    <div class="myclass">
        @using (Html.BeginForm("Index", "Predavanje", FormMethod.Get))
        {
            @Html.TextBox("pretraga")<input type="submit" value="Pretrazi" />

        }
        @using (Html.BeginForm("Index", "Predavanje"))
        {
            <input type="submit" value="Obrisi filter" />
        }

    </div>
    <table class="table table-hover mytable">
        <thead>
            <tr>
                <th>Tema predavanja</th>
                <th>Predavac</th>
                <th>Mesto</th>
                <th>Vreme</th>
				<th>Broj lajkova</th>
                <th></th>
				<th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var v in ViewBag.predavanja)
            {
            <tr>
                <td>@v.predmet</td>
                <td>@v.predavac</td>
                <td><a href="http://maps.google.com/?q= @v.mesto">@v.mesto</a></td>
                <td>@v.vreme</td>
				<td>@v.ocena</td>
                <td><a href="@Url.Action("PrijavaPredavanje", "Predavanje", new {id = v.id})">Prijavi se</a></td>
                <td><a href="@Url.Action("LikePredavanje", "Predavanje", new { id = v.id})" data-toggle="tooltip" title="Svidja mi se"><span class="fa fa-heart" fill="currentColor" ></span></a></td>                   
		        <td><a href="@Url.Action("AboutPredavanje", "Predavanje", new {id = v.id})" data-toggle="tooltip" title="Pogledaj komentare"><span class="fa fa-commenting-o"></span></a></td>
                   
            </tr>

            }
        </tbody>
    </table>
    <div class="komentari">
         @Html.Partial("_CommentPredavanje")
        </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/bootstrap-table@1.17.1/dist/bootstrap-table.min.js"></script>

</body>
</html>

Views/Predavanje/PrijavaPredavanje.cshtml
@{
    ViewBag.Title = "View";
    Layout = null;
}
@model WebPlatforma.Entites.Predavanje

<!doctype html>
<html lang="en">
<head>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">

    <!------ Include the above in your HEAD tag ---------->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Knjige</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.17.1/dist/bootstrap-table.min.css">

    <link href="~/Content/PrijavaPredavanje.css" rel="stylesheet">
</head>
<body>
    @Html.Partial("_NavBar")
    <!--ucitava sve iz baze i ubacuje fajl u Resources-->
    <div class="klasaDiv">
        @using (Html.BeginForm("UpdatePredavanje", "Predavanje", FormMethod.Post))
        {
            <div id="addbox" style=" margin-top:50px" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                <div class="panel panel-info">

                    <div class="panel-body">
                        <form method="post" action=".">
                            <input type='hidden' name='csrfmiddlewaretoken' value='XFe2rTYl9WOpV8U6X5CfbIuOZOELJ97S' />


                            <div class="form-horizontal" method="post">
                                <input type='hidden' name='csrfmiddlewaretoken' value='XFe2rTYl9WOpV8U6X5CfbIuOZOELJ97S' />

                                <div id="div_id_mail" class="form-group required">
                                    <label for="id_mail" class="control-label col-md-4  requiredField"> Email adresa<span class="asteriskField">*</span> </label>
                                    <div class="controls col-md-8 ">
                                        <input class="input-md  textinput textInput form-control" id="id_mail" maxlength="50" name="prijavljeniKorisnici" placeholder="Unesite email adresu" style="margin-bottom: 10px" type="text" />
                                       @Html.HiddenFor(a => a.id)
                                    </div>
                                </div>


                                <div class="form-group">
                                    <div class="aab controls col-md-4 "></div>
                                    <div class="controls col-md-8 ">


                                        <input type="submit" value="Prijava" />
                                      
                                    </div>
                                </div>

                            </div>

                        </form>
                    </div>
                </div>
            </div>

        }
    </div>

</body>
</html>